// Automatically generated by astro-icon
// d7f06db514c65865e6bbef5cd52a01af4778362c3347a20c220ca2d36e577f17

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "menu/about"
		| "menu/blog"
		| "menu/book"
		| "menu/categories"
		| "menu/contact"
		| "menu/cube"
		| "menu/friend"
		| "menu/heart"
		| "menu/home"
		| "menu/post"
		| "menu/project"
		| "social/bilibili"
		| "social/github"
		| "social/rss"
		| "social/support"
		| "social/zhihu";
}