// Automatically generated by astro-icon
// 12ecb7470fceb1e7d8f697d68adbdc580ef0f76ecfaf96b8cd3196edd0857f56

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "menu/about"
		| "menu/blog"
		| "menu/book"
		| "menu/categories"
		| "menu/cube"
		| "menu/friend"
		| "menu/heart"
		| "menu/home"
		| "menu/post"
		| "menu/project"
		| "social/bilibili"
		| "social/contact"
		| "social/github"
		| "social/rss"
		| "social/support"
		| "social/zhihu";
}